apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-nccyzpro
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-nccyzpro 
  name: go-nccyzpro
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-nccyzpro
    weight: 100 
